config/routes.rb
Rails.application.routes.draw do
	root 'dashboards#index'
	
	get '/search', to: 'dashboards#search'
	
	# payments urls
	get '/payments/show_token', to: 'payments#show_token' # dev only
	get '/payments/register', to: 'payments#register'  # dev only
	
    post '/payments/confirm', to: 'payments#confirm'
    post '/payments/validate', to: 'payments#validate'
    
    get '/payments/c2bsimulate', to: 'payments#c2bsimulate' #dev only
    
    post '/payments/lnm_callback', to: 'payments#lnm_callback'
    get '/payments/stk_push', to: 'payments#stkpush'

	devise_for :users, controllers: { registrations: 'users' }
		
	resources :users do
		resources :cars 
	end
	
	resources :cars do
		resources :hired_cars
	end
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
	skip_before_action :authenticate_user!, only: [:index, :search]
	
	def index
		@user = current_user
		@car = Car.first
		
		@available_cars = []
		hired = false
		data = session[:hire_car_data]
		
		if user_signed_in? and data
			if !HiredCar.find_by(car_id: data["car_id"])
			    
			    # pay for a car before hiring another
			    pending = false
			    HiredCar.all.each do |car|
			        if car.user_id == @user.id and car.payment == "pending"
			            flash[:alert] = "Please complete a pending payment first"
			            #redirect_to car_hired_cars_path(car)
			            pending = true
			            break
			        end
			    end
			    
			    if !pending
    				@hired_car = @car.hired_cars.create(data["hired_car_params"])
    				HiredCar.update(@hired_car.id, payment: 'pending') # payment defaults to 'pending'
    				HiredCar.update(@hired_car.id, user_id: @user.id)
    				
    				# add pickup and return dates to hired_cars table
    				HiredCar.update(@hired_car.id, start_date: session[:start_date])
    				HiredCar.update(@hired_car.id, end_date: session[:end_date])
    			end
			end
			
			session[:hire_car_data] = nil
			
			#render plain: params
			redirect_to car_hired_cars_path(@car)
			
		end
		
		Car.all.each do |car|
			
			HiredCar.all.each do |hired_car|
				if car.id == hired_car.car_id
					hired = true
					break
				end
			end
			
			
			if !hired
				@available_cars.push(car)
			end
			hired = false
		end
	
		if @user 
			@list_car_path = new_user_car_path(@user)
		else
			@user = User.new
			@user.id = 0
			@list_car_path = new_user_car_path(@user)
		end
		
	
	end
	
	def search
		@user = current_user
		@car = Car.first
		@available_cars = Car.all
		
		# save dates to session
		session[:start_date] = Date.parse(params[:start_date])
		session[:end_date] = Date.parse(params[:end_date])
		session[:hire_days] = session[:end_date].day - session[:start_date].day

		if !params[:model].strip.empty?
			@available_cars = @available_cars.where("model  ilike ?", '%'+params[:model]+'%')
		end
		
		if !params[:location].strip.empty?
			@available_cars = @available_cars.where("location ilike ?", '%'+params[:location]+'%')
		end
		
		cars = @available_cars
		@available_cars = []
		hired = false
		
		cars.each do |car|
			
			HiredCar.all.each do |hired_car|
				if car.id == hired_car.car_id
					hired = true
					break
				end
			end
			
			
			if !hired
				@available_cars.push(car)
			end
			hired = false
		end	
		
		render "dashboards/search_result"
	end
end

app/helpers/dashboards_helper.rb
module DashboardsHelper
end

app/views/dashboards/_list_cars.html.erb
<div class="row">
	<div class="col-md-4">
		<i class="fa fa-car fa-5x" style="color:#434371;"></i>
	</div>

	<div class="col-md-8">
		<strong>Model: </strong><em> <%= car.model %></em><br>
		<strong>Transmission: </strong><em> <%= car.transmission %></em><br>
		<strong>Pick-Up Location: </strong><em> <%= car.location %></em><br>
		<strong>Price: </strong><em> <%= car.price %> per day</em><br>
	</div>
</div>
<a href=<%= new_car_hired_car_path(car) %> class="btn btn-primary btn-fill pull-right">View</a>
<div class="clearfix"></div>
<hr>

app/views/dashboards/client_index.html.erb
<div class="wrapper">
    <div class="sidebar" data-color="blue" data-image='sidebar-5.jpg' >

    <!--

        Tip 1: you can change the color of the sidebar using: data-color="blue | azure | green | orange | red | purple"
        Tip 2: you can also add an image using data-image tag

    -->

    	<div class="sidebar-wrapper">
            <div class="logo">
                <a href="http://www.hiresafe.com" class="simple-text">
                    <%= image_tag "nice-car.jpg", class: "car-logo" %>
                </a>
            </div>

            <ul class="nav">
                <li class="active">
                    <a href= <%= root_path %> >
                        <i class="fa fa-car"></i>
                        <p>Dashboard</p>
                    </a>
                </li>

                <li>
                    <a href=<%= edit_user_registration_path%> >
                        <i class="fa fa-user"></i>
                        <p>Profile</p>
                    </a>
                </li>

            </ul>
    	</div>
    </div>

    <div class="main-panel">
        <nav class="navbar navbar-default navbar-fixed">
            <div class="container-fluid">
                <div class="navbar-header hiresafe-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href=<%= edit_user_registration_path%> ><%= current_user.name %></a>
                   
                </div>
                <div class="collapse navbar-collapse">
             
                    <ul class="nav navbar-nav navbar-right">
                        <li>
                           <a href=<%= destroy_user_session_path %> data-method="delete" >
                               Sign Out
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>


       <div class="content">
            <div class="container-fluid">
                <div class="row">
					<div class="col-md-6">
						<div class="card">
							<div class="header">
                                <h4 class="title">Amazing Cars Ready For Hire</h4>
                            </div>
                            <div class="content">
                                <% if Car.all.any? %>
									<% Car.all.each do |car| %>
										<div class="row">
											<div class="col-md-4">
												<i class="fa fa-car fa-5x" style="color:#434371;"></i>
											</div>

											<div class="col-md-8">
												<strong>Model: </strong><em> <%= car.model %></em><br>
												<strong>Transmission: </strong><em> <%= car.transmission %></em><br>
												<strong>Pick-Up Location: </strong><em> <%= car.location %></em><br>
												<strong>Price: </strong><em> <%= car.price %> per day</em><br>
											</div>
										</div>
										<hr>
									<% end %>
								<% else %>
									Unfortunately none are available for now!!
									<i class="fa fa-sad"></i>
									<i class="fa fa-sad"></i>
								<% end %>
                            </div>
						</div>
					</div>
					
						<div class="col-md-6">
							<div class="card card-glance">
								<div class="header">
									<h4 class="title">At a glance</h4>
								</div>
								<div class="content">
								   <div class="row">
										<div class="col-md-4">
											<i class="fa fa-users"></i>
											<em><strong><%= User.all.count %></strong> Users</em>
										</div>
										
										<div class="col-md-4">
											<i class="fa fa-car"></i>
											<em><strong><%= Car.all.count %></strong> Cars</em>
										</div>
										
										<div class="col-md-4">
											<i class="fa fa-road"></i>
											<em><strong><%= HiredCar.all.count %></strong> Currently Hired Cars</em>
										</div>
										
								   </div>
								   <div class="footer">
										<hr>
										<div class="row">
											<div class="col-md-6">
												<em>We have a 5 star rating.</em>
											</div>
											<div class="col-md-6 gold-color">
												<i class="fa fa-star"></i>
												<i class="fa fa-star"></i>
												<i class="fa fa-star"></i>
												<i class="fa fa-star"></i>
												<i class="fa fa-star"></i>
											</div>
										</div>
								   </div>
								</div>
							</div>
						</div>
					</div>
                </div>
            </div>




        <footer class="footer">
            <div class="container-fluid">
                <div class="pull-left">
                    <strong>Contact Us:</strong> <br>
						<i class="fa fa-phone-square"></i> +2547000000001 <br>
						<i class="fa fa-inbox"></i>  hiresafe@gmail.com <br>
                </div>
                <p class="copyright pull-right">
                    &copy; 2019 <a href="http://www.hiresafe.com">Hire Safe</a>, Just hire, no worries
                </p>
            </div>
        </footer>

    </div>
</div>

app/views/dashboards/index.html.erb
<div class="wrapper">
    <div class="sidebar" data-color="blue" data-image='sidebar-5.jpg' >

    <!--

        Tip 1: you can change the color of the sidebar using: data-color="blue | azure | green | orange | red | purple"
        Tip 2: you can also add an image using data-image tag

    -->

    	<div class="sidebar-wrapper">
            <div class="logo">
                <a href="#" class="simple-text">
                    <%= image_tag "aquarius.jpg", class: "car-logo1 img-rounded" %>
                </a>
            </div>

            <ul class="nav">
                <li class="active">
                    <a href= <%= root_path %> >
                        <i class="fa fa-car"></i>
                        <p>Dashboard</p>
                    </a>
                </li>
                
                <li class="">
                    <a href= <%= @list_car_path %> >
                        <i class="fa fa-car"></i>
                        <p>List Your Car</p>
                    </a>
                </li>
                
                <% if user_signed_in? %>
                <li>
                    <a href=<%= user_cars_path(@car) %> >
                        <i class="fa fa-key"></i>
                        <p>My Cars</p>
                    </a>
                </li>

                <li>
                    <a href=<%= car_hired_cars_path(@car) %> >
                        <i class="fa fa-key"></i>
                        <p>Hired Cars</p>
                    </a>
                </li>

                <li>
                    <a href=<%= edit_user_registration_path%> >
                        <i class="fa fa-user"></i>
                        <p>Profile</p>
                    </a>
                </li>
                
                <li class="">
                    <a href= <%= destroy_user_session_path %> data-method="delete" >
                        <i class="fa fa-user"></i>
                        <p>Sign Out</p>
                    </a>
                </li>
				<% end %>
            </ul>
    	</div>
    </div>

    <div class="main-panel">
        <nav class="navbar navbar-default navbar-fixed">
            <div class="container-fluid">
                <div class="navbar-header hiresafe-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="#"><strong>RideKali</strong></a>
                   
                </div>
                <div class="collapse navbar-collapse">
					
                    <ul class="nav navbar-nav navbar-right">
						<% if !current_user %>                    
							<li>
							   <a href=<%= new_user_session_path %> >
								   Login
								</a>
							</li>
							<li>
							   <a href=<%= new_user_registration_path %> >
								   <strong>Signup</strong>
								</a>
							</li>
						<% else %>
							<li>
							   <a href=<%= destroy_user_session_path %> data-method="delete">
								   SignOut
								</a>
							</li>
						<% end %>
                    </ul>
                </div>
            </div>
        </nav>


       <div class="content">
            <div class="container-fluid">
            
				<div class="row">
					
					<div class="col-md-6">
						<div class="card">
							<div class="header">
								<h4 class="title">Let’s find your ideal car</h4>
							</div>
							
							<div class="content">
								<%= form_tag "/search", method: "get" do %>
									
                                    
									<div class="row">
                                        <div class="col-md-12">
                                            <div class="form-group">
                                                
                                                <%= label_tag :location, "Pickup Location" %><br>
												<%= select_tag("location", options_for_select([['Nairobi', 'Nairobi'], ['Mombasa', 'Mombasa'], ['Nakuru', 'Nakuru'], ['Kisumu', 'Kisumu'], ['Eldoret', 'Eldoret']], 1), class: "form-control") %>
                                            </div>
                                        </div>
                                    </div>
                                    
                                    
									<div class="row">
                                        <div class="col-md-12">
                                            <div class="form-group">
                                                
                                                <%= label_tag :start_date, "Pickup Date" %><br>
												<%= date_field_tag :start_date, "", class: "form-control", required: "required" %>
                                            </div>
                                        </div>
                                    </div>
                                    
                                    
									<div class="row">
                                        <div class="col-md-12">
                                            <div class="form-group">
                                                
                                                <%= label_tag :end_date, "Return Date" %><br>
												<%= date_field_tag :end_date, "", class: "form-control", required: "required" %>
                                            </div>
                                        </div>
                                    </div>
                                    
                                    <div class="row">
                                        <div class="col-md-12">
                                            <div class="form-group">
                                                
                                                <%= label_tag :model, "Model" %><br>
												<%= select_tag("model", options_for_select([['Sedan', 1], ['Hatchback', 2], ['SUV', 3], ['Van', 4], ['Station Wagon', 5]], 1), class: "form-control") %>
                                            </div>
                                        </div>
                                    </div>
                                   
                                    <%= submit_tag "Search", class: "btn btn-info btn-fill pull-right" %>
                                    <div class="clearfix"></div>
								<% end %>
							</div>
						</div>
					</div>
				
				<div class="col-md-6">
						<div class="card">
							<div class="header">
								<h4 class="title">How it works</h4>
							</div>
							
							<div class="content">
								<p class="title font-weight-bold"><strong>Car Owner</strong></p>
								<em> Make a quick cash of your idle car. It's simple</em>
								<ol>
									<li>Identify your self</li>
									<li>List your car details/location 
										<a href=<%= @list_car_path %> class="btn btn-success btn-fill">Click Here</a> </li>
									<li>Connect to our clients</li>
								</ol>
								
								<p class="title font-weight-bold"><strong>Client</strong></p>
								<em>
									Fill the search form to look for cars based on your 
									budget and needs, we have plenty
								</em>
								<ol>
									<li>Search your desired cars</li>
									<li>Confirm your identity</li>
									<li>Go pickup your car and enjoy the ride</li>
								</ol>
								
								
							</div>
						</div>
					</div>
				</div>
				
                <div class="row">
					
						<div class="col-md-12">
							<div class="card card-glance">
								<div class="header">
									<h4 class="title">Amazing Cars and Products</h4>
								</div>
								<div class="content">
								   <div class="row">
										<div class="col-md-4">
											<%= image_tag "jeep.jpg", class: "car-logo" %>
										</div>
										<div class="col-md-4">
											<%= image_tag "sedan.png", class: "car-logo" %>
										</div>
										<div class="col-md-4">
											<%= image_tag "van.jpg", class: "car-logo" %>
										</div>
								   </div>
								   
								</div>
							</div>
						</div>
						
					</div>
                </div>
            </div>




        <footer class="footer">
            <div class="container-fluid">
                <div class="pull-left">
                    <strong>Contact Us:</strong> <br>
						<i class="fa fa-phone-square"></i> +2547000000001 <br>
						<i class="fa fa-inbox"></i>  hiresafe@gmail.com <br>
                </div>
                <p class="copyright pull-right">
                    &copy; 2019 <a href="#">Hire Safe</a>, Just hire, no worries
                </p>
            </div>
        </footer>

    </div>
</div>

app/views/dashboards/search_result.html.erb
<div class="wrapper">
    <div class="sidebar" data-color="blue" data-image='sidebar-5.jpg' >

    <!--

        Tip 1: you can change the color of the sidebar using: data-color="blue | azure | green | orange | red | purple"
        Tip 2: you can also add an image using data-image tag

    -->

    	<div class="sidebar-wrapper">
            <div class="logo">
                <a href="#" class="simple-text">
                    <%= image_tag "aquarius.jpg", class: "car-logo1" %>
                </a>
            </div>

            <ul class="nav">
                <li class="active">
                    <a href= <%= root_path %> >
                        <i class="fa fa-car"></i>
                        <p>Dashboard</p>
                    </a>
                </li>

                <li>
                    <a href=<%= car_hired_cars_path(@car) %> >
                        <i class="fa fa-key"></i>
                        <p>Hired Cars</p>
                    </a>
                </li>

                <li>
                    <a href=<%= edit_user_registration_path%> >
                        <i class="fa fa-user"></i>
                        <p>Profile</p>
                    </a>
                </li>

            </ul>
    	</div>
    </div>

    <div class="main-panel">
        <nav class="navbar navbar-default navbar-fixed">
            <div class="container-fluid">
                <div class="navbar-header hiresafe-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <% if @user %>
						<a class="navbar-brand" href=<%= edit_user_registration_path%> ><%= current_user.fname %></a>
					<% else %>
						<a class="navbar-brand" href="#"><strong>RideKali</strong></a>
					<% end %>
                </div>
                <div class="collapse navbar-collapse">
             
                    <ul class="nav navbar-nav navbar-right">
                        <li>
                           <a href=<%= destroy_user_session_path %> data-method="delete" >
                               Sign Out
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>


       <div class="content">
            <div class="container-fluid">
                <div class="row">
					<div class="col-md-8">
						<div class="card">
							<div class="header">
                                <h4 class="title"><%= pluralize(@available_cars.count, "car") %> found</h4>
                            </div>
                            <div class="content">
                                <% if @available_cars.any? %>
									<% @available_cars.each do |car| %>
										<div class="row">
											<div class="col-md-6">
											<% if car.image1.attached? %>
												<%= image_tag url_for(car.image1), class: "car-logo img-rounded" %>
											<% else %>
												<i class="fa fa-car fa-5x" style="color:#434371;"></i>
											<% end %>
											</div>
											
											<div class="col-md-6">
											<% if car.image2.attached? %>
												<%= image_tag url_for(car.image2), class: "car-logo img-rounded" %>
											<% end %>
											
											</div>
										</div>
										
										<div class="row">

											<div class="col-md-12">
												<strong>Model: </strong><em> <%= 
																				case car.model.to_i
																					when 1
																						"Sedan"
																					when 2
																						"Hatchback"
																					when 3
																						"SUV"
																					when 4
																						"Van"
																					when 5
																						"Station Wagon"
																					else
																						"Unspecified"
																				end %></em><br>
												<strong>Seats: </strong><em> <%= car.seats %></em><br>
												<strong>Transmission: </strong><em> <%= case car.transmission.to_i
																							when 1
																								"Automatic"
																							when 2
																								"Manual"
																							else
																								"Unspecified"
																						end  %></em><br>
												<strong>Car Insurance Number: </strong><em> <%= car.insurance_no %></em><br>
												<strong>Car Registration Number: </strong><em> <%= car.reg_no %></em><br>
												<strong>Pick-Up Location: </strong><em> <%= car.location %></em><br>
												<strong>Price: </strong><em> <%= car.price %> per day</em><br>
											</div>
										</div>
										<a href=<%= new_car_hired_car_path(car) %> class="btn btn-primary btn-fill pull-right">Book</a>
										<div class="clearfix"></div>
										<hr>
									<% end %>
								<% else %>
									<p class="text-warning">Unfortunately none are available for now, Try different search keywords.</p>
									<%= form_tag "/search", method: "get" do %>
									
                                    
									<div class="row">
                                        <div class="col-md-12">
                                            <div class="form-group">
                                                
                                                <%= label_tag :location, "Pickup Location" %><br>
												<%= select_tag("location", options_for_select([['Nairobi', 'Nairobi'], ['Mombasa', 'Mombasa'], ['Nakuru', 'Nakuru'], ['Kisumu', 'Kisumu'], ['Eldoret', 'Eldoret']], 1), class: "form-control") %>
                                            </div>
                                        </div>
                                    </div>
                                    
                                    <div class="row">
                                        <div class="col-md-12">
                                            <div class="form-group">
                                                
                                                <%= label_tag :start_date, "Pickup Date" %><br>
												<%= date_field_tag :start_date, "", class: "form-control", required: "required"  %>
                                            </div>
                                        </div>
                                    </div>
                                    
                                    
									<div class="row">
                                        <div class="col-md-12">
                                            <div class="form-group">
                                                
                                                <%= label_tag :end_date, "Return Date" %><br>
												<%= date_field_tag :end_date, "", class: "form-control", required: "required"  %>
                                            </div>
                                        </div>
                                    </div>
                                    
                                    <div class="row">
                                        <div class="col-md-12">
                                            <div class="form-group">
                                                
                                                <%= label_tag :model, "Model" %><br>
												<%= select_tag("model", options_for_select([['Sedan', 1], ['Hatchback', 2], ['SUV', 3], ['Van', 4], ['Station Wagon', 5]], 1), class: "form-control") %>
                                            </div>
                                        </div>
                                    </div>
                                   
                                    <%= submit_tag "Search", class: "btn btn-info btn-fill pull-right" %>
                                    <div class="clearfix"></div>
								<% end %>
								<% end %>
                            </div>
						</div>
					</div>
					
						<div class="col-md-4">
							<div class="card card-glance">
								<div class="header">
									<h4 class="title">At a glance</h4>
								</div>
								<div class="content">
								   <div class="row">
										<div class="col-md-4">
											<i class="fa fa-users"></i>
											<em><strong><%= User.all.count %></strong> Users</em>
										</div>
										
										<div class="col-md-4">
											<i class="fa fa-car"></i>
											<em><strong><%= Car.all.count %></strong> Cars</em>
										</div>
										
										<div class="col-md-4">
											<i class="fa fa-road"></i>
											<em><strong><%= HiredCar.all.count %></strong> Currently Hired Cars</em>
										</div>
										
								   </div>
								   <div class="footer">
										<hr>
										<div class="row">
											<div class="col-md-6">
												<em>We have a 5 star rating.</em>
											</div>
											<div class="col-md-6 gold-color">
												<i class="fa fa-star"></i>
												<i class="fa fa-star"></i>
												<i class="fa fa-star"></i>
												<i class="fa fa-star"></i>
												<i class="fa fa-star"></i>
											</div>
										</div>
								   </div>
								</div>
							</div>
						</div>
					</div>
                </div>
            </div>




        <footer class="footer">
            <div class="container-fluid">
                <div class="pull-left">
                    <strong>Contact Us:</strong> <br>
						<i class="fa fa-phone-square"></i> +2547000000001 <br>
						<i class="fa fa-inbox"></i>  hiresafe@gmail.com <br>
                </div>
                <p class="copyright pull-right">
                    &copy; 2019 <a href="#">Hire Safe</a>, Just hire, no worries
                </p>
            </div>
        </footer>

    </div>
</div>