config/routes.rb
Rails.application.routes.draw do
	root 'dashboards#index'
	
	get '/search', to: 'dashboards#search'
	
	# payments urls
	get '/payments/show_token', to: 'payments#show_token' # dev only
	get '/payments/register', to: 'payments#register'  # dev only
	
    post '/payments/confirm', to: 'payments#confirm'
    post '/payments/validate', to: 'payments#validate'
    
    get '/payments/c2bsimulate', to: 'payments#c2bsimulate' #dev only
    
    post '/payments/lnm_callback', to: 'payments#lnm_callback'
    get '/payments/stk_push', to: 'payments#stkpush'

	devise_for :users, controllers: { registrations: 'users' }
		
	resources :users do
		resources :cars 
	end
	
	resources :cars do
		resources :hired_cars
	end
end

app/models/car.rb
class Car < ApplicationRecord
	belongs_to :user
	has_many :hired_cars
	
	has_one_attached :image1
	has_one_attached :image2
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
	skip_before_action :authenticate_user!, only: [:new, ]
	
	def index
	    @user = current_user
		@cars = @user.cars
	end
	
	def edit
	    @user = current_user
		@car = Car.find_by(id: params[:id])
	end
	
	def new
		if user_signed_in?
			@user = User.find_by(id: params[:user_id])
		else
			flash[:alert] = "To list a car, please signin first"
			redirect_to new_user_session_path
		end
		
	end
	
	def create
		@user = User.find_by(id: params[:user_id])
		@car = @user.cars.create(car_params)
		
		case @car.model.to_i
		when 1	# sedan
			Car.update(@car.id, price: 2500)
		when 2	# hatchback
			Car.update(@car.id, price: 2000)
		when 3	# SUV
			Car.update(@car.id, price: 10000)
		when 4	# van
			Car.update(@car.id, price: 7500)
		when 5	# station wagon
			Car.update(@car.id, price: 2500)
		else
			Car.update(@car.id, price: 00) # unspecified
		end
		
		flash[:notice] = "Your Car Has Successfully Been Listed"
		redirect_to root_path
	end
	
	def update
	    @user = current_user
	    @car = Car.find_by(id: params[:id])
	    @car.update(car_params)
	    
	    redirect_to user_cars_path(@user)
	end
	
	private
    def car_params
      params.require(:car).permit(:model, :transmission, :location, :seats, :reg_no, :insurance_no, :image1, :image2)
    end
end

app/helpers/cars_helper.rb
module CarsHelper
end

app/views/cars/edit.html.erb
<div class="wrapper">
    <div class="sidebar" data-color="blue" data-image='sidebar-5.jpg' >

    <!--

        Tip 1: you can change the color of the sidebar using: data-color="blue | azure | green | orange | red | purple"
        Tip 2: you can also add an image using data-image tag

    -->

    	<div class="sidebar-wrapper">
            <div class="logo">
                <a href="http://www.hiresafe.com" class="simple-text">
                    <%= image_tag "aquarius.jpg", class: "car-logo1" %>
                </a>
            </div>

            <ul class="nav">
                <li class="active">
                    <a href= <%= root_path %> >
                        <i class="fa fa-car"></i>
                        <p>Dashboard</p>
                    </a>
                </li>
				
				<% if user_signed_in? %>

					<li>
						<a href=<%= edit_user_registration_path %> >
							<i class="fa fa-user"></i>
							<p>Profile</p>
						</a>
					</li>
			 <% end %>

            </ul>
    	</div>
    </div>

    <div class="main-panel">
        <nav class="navbar navbar-default navbar-fixed">
            <div class="container-fluid">
                <div class="navbar-header hiresafe-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>

					<% if @user %>
						<a class="navbar-brand" href=<%= edit_user_registration_path%> ><%= current_user.fname %></a>
					<% else %>
						<a class="navbar-brand" href=<%= root_path %> ><strong>RideKali</strong></a>
					<% end %>
                </div>
                <div class="collapse navbar-collapse">
             
                    <ul class="nav navbar-nav navbar-right">
                        <li>
                           <a href=<%= destroy_user_session_path %> data-method="delete" >
                               Sign Out
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>


       <div class="content">
            <div class="container-fluid">
                <div class="row">
					<div class="col-md-6">
						<div class="card">
							<div class="header">
                                <h4 class="title">Edit Car</h4>
                            </div>
                            <div class="content">
								<%= form_for @car, local: true do |form| %>
									<div class="row">
                                        <div class="col-md-12">
											<div class="field form-group">
												<%= form.label :model %><br />
												<%= select_tag("car[model]", options_for_select([['Sedan', 1], ['Hatchback', 2], ['SUV', 3], ['Van', 4], ['Station Wagon', 5]], @car.model), class: "form-control") %>
											 </div>

                                        </div>
                                    </div>
                                                                       
									<div class="row">
                                        <div class="col-md-12">
											<div class="field form-group">
												<%= form.label :seats %><br />
												<%= select_tag("car[seats]", options_for_select([['4', 4], ['5', 5], ['7', 7], ['10', 10], ['14', 14]], @car.seats), class: "form-control") %>
											 </div>

                                        </div>
                                    </div>
                                                                       
									<div class="row">
                                        <div class="col-md-12">
                                            <div class="field form-group">
												<%= form.label :transmission %><br />
												<%= select_tag("car[transmission]", options_for_select([['Automatic', 1], ['Manual', 2]], @car.transmission), class: "form-control") %>
											</div>
                                        </div>
                                    </div>
                                    
                                                                       
									<div class="row">
                                        <div class="col-md-12">
                                            <div class="field form-group">
												<%= form.label :pickup_location %><br />
												<%= select_tag("car[location]", options_for_select([['Nairobi', 'Nairobi'], ['Mombasa', 'Mombasa'], ['Nakuru', 'Nakuru'], ['Kisumu', 'Kisumu'], ['Eldoret', 'Eldoret']], @car.location), class: "form-control") %>
											</div>
                                        </div>
                                    </div>
                                                                        
                                    
									<div class="row">
                                        <div class="col-md-12">
                                            <div class="form-group">
                                                
                                                <%= form.label :car_registration_number %><br>
												<%= form.text_field :reg_no, class: "form-control" %>
                                            </div>
                                        </div>
                                    </div>
                                    
									<div class="row">
                                        <div class="col-md-12">
                                            <div class="form-group">
                                                
                                                <%= form.label :car_insurance_number %><br>
												<%= form.text_field :insurance_no, class: "form-control" %>
                                            </div>
                                        </div>
                                    </div>

								  <div class="field form-group">
									<%= form.label :car_image %><br />
									<%= form.file_field :image1, autofocus: true, class: "file-input" %><br>
									<%= form.file_field :image2, autofocus: true, class: "file-input" %>
								  </div>

                                    <%= form.submit "Update", class: "btn btn-info btn-fill pull-right" %>
                                    <div class="clearfix"></div>
								<% end %>
								
								
                            
                            </div>
						</div>
					</div>
					
						<div class="col-md-6">
							<div class="card card-glance">
								<div class="header">
									<h4 class="title">At a glance</h4>
								</div>
								<div class="content">
								   <div class="row">
										<div class="col-md-4">
											<i class="fa fa-users"></i>
											<em><strong><%= User.all.count %></strong> Users</em>
										</div>
										
										<div class="col-md-4">
											<i class="fa fa-car"></i>
											<em><strong><%= Car.all.count %></strong> Cars</em>
										</div>
										
										<div class="col-md-4">
											<i class="fa fa-road"></i>
											<em><strong><%= HiredCar.all.count %></strong> Currently Hired Cars</em>
										</div>
								   </div>
								   <div class="footer">
										<hr>
										<div class="row">
											<div class="col-md-6">
												<em>We have a 5 star rating.</em>
											</div>
											<div class="col-md-6 gold-color">
												<i class="fa fa-star"></i>
												<i class="fa fa-star"></i>
												<i class="fa fa-star"></i>
												<i class="fa fa-star"></i>
												<i class="fa fa-star"></i>
											</div>
										</div>
								   </div>
								</div>
							</div>
						</div>
					</div>
                </div>
            </div>




        <footer class="footer">
            <div class="container-fluid">
                <div class="pull-left">
                    <strong>Contact Us:</strong> <br>
						<i class="fa fa-phone-square"></i> +2547000000001 <br>
						<i class="fa fa-inbox"></i>  hiresafe@gmail.com <br>
                </div>
                <p class="copyright pull-right">
                    &copy; 2019 <a href="http://www.hiresafe.com">Hire Safe</a>, Just hire, no worries
                </p>
            </div>
        </footer>

    </div>
</div>

app/views/cars/index.html.erb
<div class="wrapper">
    <div class="sidebar" data-color="blue" data-image='sidebar-5.jpg' >

    <!--

        Tip 1: you can change the color of the sidebar using: data-color="blue | azure | green | orange | red | purple"
        Tip 2: you can also add an image using data-image tag

    -->

    	<div class="sidebar-wrapper">
            <div class="logo">
                <a href="#" class="simple-text">
                    <%= image_tag "aquarius.jpg", class: "car-logo1" %>
                </a>
            </div>

            <ul class="nav">
                <li class="active">
                    <a href= <%= root_path %> >
                        <i class="fa fa-car"></i>
                        <p>Dashboard</p>
                    </a>
                </li>

                <li>
                    <a href=<%= edit_user_registration_path%> >
                        <i class="fa fa-user"></i>
                        <p>Profile</p>
                    </a>
                </li>

            </ul>
    	</div>
    </div>

    <div class="main-panel">
        <nav class="navbar navbar-default navbar-fixed">
            <div class="container-fluid">
                <div class="navbar-header hiresafe-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <% if @user %>
						<a class="navbar-brand" href=<%= edit_user_registration_path%> ><%= current_user.fname %></a>
					<% else %>
						<a class="navbar-brand" href="#"><strong>RideKali</strong></a>
					<% end %>
                </div>
                <div class="collapse navbar-collapse">
             
                    <ul class="nav navbar-nav navbar-right">
                        <li>
                           <a href=<%= destroy_user_session_path %> data-method="delete" >
                               Sign Out
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>


       <div class="content">
            <div class="container-fluid">
                <div class="row">
					<div class="col-md-8">
						<div class="card">
							<div class="header">
                                <h4 class="title">Your Listed Cars</h4>
                            </div>
                            <div class="content">
                                <% if @cars.any? %>
									<% @cars.each do |car| %>
										<div class="row">
											<div class="col-md-6">
											<% if car.image1.attached? %>
												<%= image_tag url_for(car.image1), class: "car-logo img-rounded" %>
											<% else %>
												<i class="fa fa-car fa-5x" style="color:#434371;"></i>
											<% end %>
											</div>
											
											<div class="col-md-6">
											<% if car.image2.attached? %>
												<%= image_tag url_for(car.image2), class: "car-logo img-rounded" %>
											<% end %>
											
											</div>
										</div>
										
										<div class="row">

											<div class="col-md-12">
												<strong>Model: </strong><em> <%= 
																				case car.model.to_i
																					when 1
																						"Sedan"
																					when 2
																						"Hatchback"
																					when 3
																						"SUV"
																					when 4
																						"Van"
																					when 5
																						"Station Wagon"
																					else
																						"Unspecified"
																				end %></em><br>
												<strong>Seats: </strong><em> <%= car.seats %></em><br>
												<strong>Transmission: </strong><em> <%= case car.transmission.to_i
																							when 1
																								"Automatic"
																							when 2
																								"Manual"
																							else
																								"Unspecified"
																						end  %></em><br>
												<strong>Car Insurance Number: </strong><em> <%= car.insurance_no %></em><br>
												<strong>Car Registration Number: </strong><em> <%= car.reg_no %></em><br>
												<strong>Pick-Up Location: </strong><em> <%= car.location %></em><br>
												<strong>Price: </strong><em> <%= car.price %> per day</em><br>
											</div>
										</div>
										<a href=<%= edit_user_car_path(@user, car) %> class="btn btn-primary btn-fill pull-right">Edit</a>
										<div class="clearfix"></div>
										<hr>
									<% end %>
								<% else %>
								    <div class="row">
								        <div class="col-md-6">
								            <div class="card">
								                <div class="header">
								                    <h3 class="title">You Haven't Listed Cars Yet</h3>
								                </div>
								            </div>
								        </div>
								    </div>
								<% end %>
                            </div>
						</div>
					</div>
					
						<div class="col-md-4">
							<div class="card card-glance">
								<div class="header">
									<h4 class="title">At a glance</h4>
								</div>
								<div class="content">
								   <div class="row">
										<div class="col-md-4">
											<i class="fa fa-users"></i>
											<em><strong><%= User.all.count %></strong> Users</em>
										</div>
										
										<div class="col-md-4">
											<i class="fa fa-car"></i>
											<em><strong><%= Car.all.count %></strong> Cars</em>
										</div>
										
										<div class="col-md-4">
											<i class="fa fa-road"></i>
											<em><strong><%= HiredCar.all.count %></strong> Currently Hired Cars</em>
										</div>
										
								   </div>
								   <div class="footer">
										<hr>
										<div class="row">
											<div class="col-md-6">
												<em>We have a 5 star rating.</em>
											</div>
											<div class="col-md-6 gold-color">
												<i class="fa fa-star"></i>
												<i class="fa fa-star"></i>
												<i class="fa fa-star"></i>
												<i class="fa fa-star"></i>
												<i class="fa fa-star"></i>
											</div>
										</div>
								   </div>
								</div>
							</div>
						</div>
					</div>
                </div>
            </div>




        <footer class="footer">
            <div class="container-fluid">
                <div class="pull-left">
                    <strong>Contact Us:</strong> <br>
						<i class="fa fa-phone-square"></i> +2547000000001 <br>
						<i class="fa fa-inbox"></i>  hiresafe@gmail.com <br>
                </div>
                <p class="copyright pull-right">
                    &copy; 2019 <a href="#">Hire Safe</a>, Just hire, no worries
                </p>
            </div>
        </footer>

    </div>
</div>

app/views/cars/new.html.erb
<div class="wrapper">
    <div class="sidebar" data-color="blue" data-image='sidebar-5.jpg' >

    <!--

        Tip 1: you can change the color of the sidebar using: data-color="blue | azure | green | orange | red | purple"
        Tip 2: you can also add an image using data-image tag

    -->

    	<div class="sidebar-wrapper">
            <div class="logo">
                <a href="http://www.hiresafe.com" class="simple-text">
                    <%= image_tag "aquarius.jpg", class: "car-logo1" %>
                </a>
            </div>

            <ul class="nav">
                <li class="active">
                    <a href= <%= root_path %> >
                        <i class="fa fa-car"></i>
                        <p>Dashboard</p>
                    </a>
                </li>
				
				<% if user_signed_in? %>

					<li>
						<a href=<%= edit_user_registration_path %> >
							<i class="fa fa-user"></i>
							<p>Profile</p>
						</a>
					</li>
			 <% end %>

            </ul>
    	</div>
    </div>

    <div class="main-panel">
        <nav class="navbar navbar-default navbar-fixed">
            <div class="container-fluid">
                <div class="navbar-header hiresafe-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>

					<% if @user %>
						<a class="navbar-brand" href=<%= edit_user_registration_path%> ><%= current_user.fname %></a>
					<% else %>
						<a class="navbar-brand" href=<%= root_path %> ><strong>RideKali</strong></a>
					<% end %>
                </div>
                <div class="collapse navbar-collapse">
             
                    <ul class="nav navbar-nav navbar-right">
                        <li>
                           <a href=<%= destroy_user_session_path %> data-method="delete" >
                               Sign Out
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>


       <div class="content">
            <div class="container-fluid">
                <div class="row">
					<div class="col-md-6">
						<div class="card">
							<div class="header">
                                <h4 class="title">New Car</h4>
                            </div>
                            <div class="content">
								<%= form_with(model: [ @user, @user.cars.build ], local: true) do |form| %>
									<div class="row">
                                        <div class="col-md-12">
											<div class="field form-group">
												<%= form.label :model %><br />
												<%= select_tag("car[model]", options_for_select([['Sedan', 1], ['Hatchback', 2], ['SUV', 3], ['Van', 4], ['Station Wagon', 5]], 1), class: "form-control") %>
											 </div>

                                        </div>
                                    </div>
                                                                       
									<div class="row">
                                        <div class="col-md-12">
											<div class="field form-group">
												<%= form.label :seats %><br />
												<%= select_tag("car[seats]", options_for_select([['4', 4], ['5', 5], ['7', 7], ['10', 10], ['14', 14]], 1), class: "form-control") %>
											 </div>

                                        </div>
                                    </div>
                                                                       
									<div class="row">
                                        <div class="col-md-12">
                                            <div class="field form-group">
												<%= form.label :transmission %><br />
												<%= select_tag("car[transmission]", options_for_select([['Automatic', 1], ['Manual', 2]], 1), class: "form-control") %>
											</div>
                                        </div>
                                    </div>
                                    
                                                                       
									<div class="row">
                                        <div class="col-md-12">
                                            <div class="field form-group">
												<%= form.label :pickup_location %><br />
												<%= select_tag("car[location]", options_for_select([['Nairobi', 'Nairobi'], ['Mombasa', 'Mombasa'], ['Nakuru', 'Nakuru'], ['Kisumu', 'Kisumu'], ['Eldoret', 'Eldoret']], 1), class: "form-control") %>
											</div>
                                        </div>
                                    </div>
                                                                        
                                    
									<div class="row">
                                        <div class="col-md-12">
                                            <div class="form-group">
                                                
                                                <%= form.label :car_registration_number %><br>
												<%= form.text_field :reg_no, class: "form-control" %>
                                            </div>
                                        </div>
                                    </div>
                                    
									<div class="row">
                                        <div class="col-md-12">
                                            <div class="form-group">
                                                
                                                <%= form.label :car_insurance_number %><br>
												<%= form.text_field :insurance_no, class: "form-control" %>
                                            </div>
                                        </div>
                                    </div>

								  <div class="field form-group">
									<%= form.label :car_image %><br />
									<%= form.file_field :image1, autofocus: true, class: "file-input" %><br>
									<%= form.file_field :image2, autofocus: true, class: "file-input" %>
								  </div>

                                    <%= form.submit "Add Car", class: "btn btn-info btn-fill pull-right" %>
                                    <div class="clearfix"></div>
								<% end %>
								
								
                            
                            </div>
						</div>
					</div>
					
						<div class="col-md-6">
							<div class="card card-glance">
								<div class="header">
									<h4 class="title">At a glance</h4>
								</div>
								<div class="content">
								   <div class="row">
										<div class="col-md-4">
											<i class="fa fa-users"></i>
											<em><strong><%= User.all.count %></strong> Users</em>
										</div>
										
										<div class="col-md-4">
											<i class="fa fa-car"></i>
											<em><strong><%= Car.all.count %></strong> Cars</em>
										</div>
										
										<div class="col-md-4">
											<i class="fa fa-road"></i>
											<em><strong><%= HiredCar.all.count %></strong> Currently Hired Cars</em>
										</div>
								   </div>
								   <div class="footer">
										<hr>
										<div class="row">
											<div class="col-md-6">
												<em>We have a 5 star rating.</em>
											</div>
											<div class="col-md-6 gold-color">
												<i class="fa fa-star"></i>
												<i class="fa fa-star"></i>
												<i class="fa fa-star"></i>
												<i class="fa fa-star"></i>
												<i class="fa fa-star"></i>
											</div>
										</div>
								   </div>
								</div>
							</div>
						</div>
					</div>
                </div>
            </div>




        <footer class="footer">
            <div class="container-fluid">
                <div class="pull-left">
                    <strong>Contact Us:</strong> <br>
						<i class="fa fa-phone-square"></i> +2547000000001 <br>
						<i class="fa fa-inbox"></i>  hiresafe@gmail.com <br>
                </div>
                <p class="copyright pull-right">
                    &copy; 2019 <a href="http://www.hiresafe.com">Hire Safe</a>, Just hire, no worries
                </p>
            </div>
        </footer>

    </div>
</div>